database:
  type: mysql
  sqlite:
    file: "auctions.sqlite"
  mysql:
    host: localhost
    username: root
    password: password
    schema: "piggyauctions"
  worker-limt: 1
economy:
  provider: EconomyS
